vars:
  - experiments_dir: '//10.164.3.225/spagnuolo/Dati'
  - matlab_scripts: 'functions'

stages:
  reproduce_shivaunix_analysis:
    # Questa lista ora viene pescata direttamente e automaticamente da params.yaml
    foreach: ${experiments} 
    do:
      cmd: >
        matlab -batch 
        "addpath(genpath('${matlab_scripts}')); 
        run_pipeline_from_log('${experiments_dir}/${item}/${item}RED.json')"

      deps:
        - ${experiments_dir}/${item}/${item}RED.json
        - ${matlab_scripts}/

      outs:
        - ${experiments_dir}/${item}/${item}RED.mat:
            cache: false